name = "worker-template"
type = "webpack"
account_id = ""
zone_id = ""
workers_dev = true
vars = { DEBUG = true }
webpack_config = "./api/webpack.config.js"

[site]
bucket = "./frontend/build"
entry-point = "./api"
